[package]
name = "egomoose/wally-package-access"
version = "0.1.2"
license = "MIT"
description = "Provides access to other wally dependencies as instances instead of requiring them"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]