[package]
name = "egomoose/wally-package-access"
version = "0.2.0"
license = "MIT"
description = "Provides access to other wally dependencies as instances instead of requiring them"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
Promise4 = "evaera/promise@4.0.0"
Promise3 = "evaera/promise@3.2.1"
PlayerModule = "upliftgames/playermodule@578.0.5780566"
Janitor = "howmanysmall/janitor@1.15.6"
Knit = "sleitnick/knit@1.5.1"